# Change these first
owner: goquantio # Your GitHub organization or username, where this repository lives
repo: crypto-monitor # The name of this repository

sites:
  - name: Binance - aggTrades
    url: https://data.binance.com/api/v3/aggTrades
  - name: Binance - avgPrice
    url: https://data.binance.com/api/v3/avgPrice
  - name: Binance - depth
    url: https://data.binance.com/api/v3/depth
  - name: Binance - exchangeInfo
    url: https://data.binance.com/api/v3/exchangeInfo
  - name: Binance - klines
    url: https://data.binance.com/api/v3/klines
  - name: Binance - ping
    url: https://data.binance.com/api/v3/ping
  - name: Binance - ticker
    url: https://data.binance.com/api/v3/ticker
  - name: Binance - ticker/24hr
    url: https://data.binance.com/api/v3/ticker/24hr
  - name: Binance - ticker/bookTicker
    url: https://data.binance.com/api/v3/ticker/bookTicker
  - name: Binance - ticker/price
    url: https://data.binance.com/api/v3/ticker/price
  - name: Binance - time
    url: https://data.binance.com/api/v3/time
  - name: Binance - trades
    url: https://data.binance.com/api/v3/trades
  - name: Binance - uiKlines
    url: https://data.binance.com/api/v3/uiKlines

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /crypto-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Crypto Monitor
  introTitle: "**Crypto Monitor** monitors the cryto exchange apis."
  introMessage: Monitors relate to REST connections and do not include websockets
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
