# Change these first
owner: goquantio # Your GitHub organization or username, where this repository lives
repo: crypto-monitor # The name of this repository

sites:
  - name: Binance - Ping
    url: https://api.binance.us/api/v3/ping
  - name: Binance - Server Time
    url: https://api.binance.us/api/v3/time
  - name: Binance - Aggregate Trades (BTCUSDT/limit=500)
    url: https://api.binance.us/api/v3/aggTrades?symbol=BTCUSDT&limit=500
  - name: Binance - Average Price - (BTCUSDT)
    url: https://api.binance.us/api/v3/avgPrice?symbol=BTCUSDT
  - name: Binance - Depth - (BTCUSDT)
    url: https://api.binance.us/api/v3/depth?symbol=BTCUSDT
  - name: Binance - exchangeInfo
    url: https://api.binance.us/api/v3/exchangeInfo
  - name: Binance - Klines - (BTCUSDT/1 Day Interval)
    url: https://api.binance.us/api/v3/klines?symbol=BTCUSDT&interval=1d
  - name: Binance - UIKlines (BTCUSDT/1 Day Interval/Limit = 500)
    url: https://api.binance.us/api/v3/uiKlines?symbol=BTCUSDT&interval=1d&limit=500
  - name: Binance - Ticker - (BTCUSDT)
    url: https://api.binance.us/api/v3/ticker?symbol=BTCUSDT
  - name: Binance - Ticker/24hr
    url: https://api.binance.us/api/v3/ticker/24hr
  - name: Binance - Ticker/Book Ticker
    url: https://api.binance.us/api/v3/ticker/bookTicker
  - name: Binance - Ticker/Price
    url: https://api.binance.us/api/v3/ticker/price
  - name: Binance - trades - (BTCUSDT)
    url: https://api.binance.us/api/v3/trades?symbol=BTCUSDT

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /crypto-monitor
  logoUrl: https://res.cloudinary.com/dfsht1snd/image/upload/v1675451285/website/social/goquant.png
  name: Crypto Monitor
  introTitle: "**Crypto Monitor** monitors the cryto exchange apis."
  introMessage: Monitors relate to REST connections and do not include websockets
  navbar:
    - title: GoQuant
      href: https://goquant.io
    - title: GitHub
      href: https://github.com/goquantio

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
