# Change these first
owner: goquantio # Your GitHub organization or username, where this repository lives
repo: crypto-monitor # The name of this repository

sites:
  # Server Time
  - name: Server Time
    url: https://api.binance.us/api/v3/time
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671212066/website/solutions/exchanges/binance-light.png

  - name: Server Time
    url: https://api-testnet.bybit.com/v2/public/time
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211942/website/solutions/exchanges/bybit-light.png

  - name: Server Time
    url: https://api.kraken.com/0/public/Time
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211943/website/solutions/exchanges/kraken.png
    
  - name: Server Time
    url: https://api-pub.bitfinex.com/v2/platform/status
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211943/website/solutions/exchanges/bitfinex-light.png


  # Orderbook
  - name: Orderbook (BTCUSDT)
    url: https://api.binance.us/api/v3/depth?symbol=BTCUSDT
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671212066/website/solutions/exchanges/binance-light.png

  - name: Orderbook (BTCUSDT)
    url: https://api-testnet.bybit.com/public/linear/kline?symbol=BTCUSDT&interval=1&limit=2&from=1581231260
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211942/website/solutions/exchanges/bybit-light.png

  - name: Orderbook (XBTUSD)
    url: https://api.kraken.com/0/public/Depth?pair=XBTUSD
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211943/website/solutions/exchanges/kraken.png

  - name: Orderbook (XBTUSD)
    url: https://api-pub.bitfinex.com/v2/book/tBTCUSD/P0?len=25
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211943/website/solutions/exchanges/bitfinex-light.png

  # OHLCV
  - name: OHLCV (BTCUSDT/1 Day Interval)
    url: https://api.binance.us/api/v3/klines?symbol=BTCUSDT&interval=1d
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671212066/website/solutions/exchanges/binance-light.png

  - name: OHLCV (BTCUSDT/1 Day Interval/Limit = 2)
    url: https://api-testnet.bybit.com/public/linear/kline?symbol=BTCUSDT&interval=1&limit=2&from=1581231260
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211942/website/solutions/exchanges/bybit-light.png

  - name: OHLCV (XBTUSD)
    url: https://api.kraken.com/0/public/OHLC?pair=XBTUSD
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211943/website/solutions/exchanges/kraken.png
    
  - name: OHLCV (XBTUSD)
    url: https://api-pub.bitfinex.com/v2/candles/trade:1m:tBTCUSD/hist?limit=120&sort=-1
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211943/website/solutions/exchanges/bitfinex-light.png

  # Symbol Pair Price
  - name: Symbol Pairs (BTCUSDT)
    url: https://api.binance.us/api/v3/ticker?symbol=BTCUSDT
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671212066/website/solutions/exchanges/binance-light.png

  - name: Symbol Pairs (BTCUSDT/Limit = 500)
    url: https://api-testnet.bybit.com/public/linear/recent-trading-records?symbol=BTCUSDT&limit=500
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211942/website/solutions/exchanges/bybit-light.png

  - name: Symbol Pairs (XBT/ETH)
    url: https://api.kraken.com/0/public/AssetPairs?pair=XXBTZUSD,XETHXXBT
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211943/website/solutions/exchanges/kraken.png

  - name: Symbol Pairs (XBT/ETH)
    url: https://api-pub.bitfinex.com/v2/ticker/tBTCUSD
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211943/website/solutions/exchanges/bitfinex-light.png


  # Recent Trading
  - name: Recent Trading - (BTCUSDT)
    url: https://api.binance.us/api/v3/trades?symbol=BTCUSDT
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671212066/website/solutions/exchanges/binance-light.png

  - name: Recent Trading - (BTCUSDT/Limit = 500)
    url: https://api-testnet.bybit.com/public/linear/recent-trading-records?symbol=BTCUSDT&limit=500
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211942/website/solutions/exchanges/bybit-light.png

  - name: Recent Trading - (XBTUSD)
    url: https://api.kraken.com/0/public/Trades?pair=XBTUSD
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211943/website/solutions/exchanges/kraken.png

  # Binance
  - name: Aggregate Trades (BTCUSDT/limit=500)
    url: https://api.binance.us/api/v3/aggTrades?symbol=BTCUSDT&limit=500
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671212066/website/solutions/exchanges/binance-light.png

  - name: Average Price - (BTCUSDT)
    url: https://api.binance.us/api/v3/avgPrice?symbol=BTCUSDT
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671212066/website/solutions/exchanges/binance-light.png

  - name: exchangeInfo
    url: https://api.binance.us/api/v3/exchangeInfo
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671212066/website/solutions/exchanges/binance-light.png

  - name: Ping
    url: https://api.binance.us/api/v3/ping
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671212066/website/solutions/exchanges/binance-light.png

  - name: UIKlines (BTCUSDT/1 Day Interval/Limit = 500)
    url: https://api.binance.us/api/v3/uiKlines?symbol=BTCUSDT&interval=1d&limit=500
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671212066/website/solutions/exchanges/binance-light.png


  - name: Ticker/24hr
    url: https://api.binance.us/api/v3/ticker/24hr
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671212066/website/solutions/exchanges/binance-light.png

  - name: Ticker/Book Ticker
    url: https://api.binance.us/api/v3/ticker/bookTicker
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671212066/website/solutions/exchanges/binance-light.png

  - name: Ticker/Price
    url: https://api.binance.us/api/v3/ticker/price
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671212066/website/solutions/exchanges/binance-light.png

  
  # ByBit

  - name: Kline - (BTCUSDT/Interval 1/From Now)
    url: https://api-testnet.bybit.com/public/linear/kline?symbol=BTCUSDT&interval=1&limit=2&from=1581231260
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211942/website/solutions/exchanges/bybit-light.png

  - name: Recent Trading - (BTCUSDT/Limit = 500)
    url: https://api-testnet.bybit.com/public/linear/recent-trading-records?symbol=BTCUSDT&limit=500
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211942/website/solutions/exchanges/bybit-light.png


  - name: Latest Funding Rate - (BTCUSDT/Limit = 500)
    url: https://api-testnet.bybit.com/public/linear/funding/prev-funding-rate?symbol=BTCUSDT
    icon: https://res.cloudinary.com/dfsht1snd/image/upload/v1671211942/website/solutions/exchanges/bybit-light.png

  # Kraken

    
    
    




status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /crypto-monitor
  logoUrl: https://res.cloudinary.com/dfsht1snd/image/upload/v1675451285/website/social/goquant.png
  name: Crypto Monitor
  introTitle: "**Crypto Monitor** monitors the cryto exchange apis."
  introMessage: Monitors relate to REST connections and do not include websockets
  navbar:
    - title: GoQuant
      href: https://goquant.io
    - title: GitHub
      href: https://github.com/goquantio/crypto-monitor

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
