# Change these first
owner: goquantio # Your GitHub organization or username, where this repository lives
repo: crypto-monitor # The name of this repository

sites:
  - name: Binance - ping
    url: https://api.binance.us/api/v3/ping
  - name: Binance - time
    url: https://api.binance.us/fapi/v1/time
  - name: Binance - aggTrades
    url: https://api.binance.us/api/v3/aggTrades
  - name: Binance - avgPrice - BTCUSDT
    url: https://api.binance.us/api/v3/avgPrice?symbol=BTCUSDT
  - name: Binance - depth - BTCUSDT
    url: https://api.binance.us/api/v3/depth?symbol=BTCUSDT
  - name: Binance - exchangeInfo
    url: https://api.binance.us/api/v3/exchangeInfo
  - name: Binance - klines - BTCUSDT - 1 day
    url: https://api.binance.us/api/v3/klines?symbol=BTCUSDT&interval=1d
  - name: Binance - ticker - BTCUSDT
    url: https://api.binance.us/api/v3/ticker?symbol=BTCUSDT
  - name: Binance - ticker/24hr
    url: https://api.binance.us/api/v3/ticker/24hr
  - name: Binance - ticker/bookTicker
    url: https://api.binance.us/api/v3/ticker/bookTicker
  - name: Binance - ticker/price
    url: https://api.binance.us/api/v3/ticker/price
  - name: Binance - time
    url: https://api.binance.us/api/v3/time
  - name: Binance - trades - BTCUSDT
    url: https://api.binance.us/api/v3/trades?symbol=BTCUSDT
  - name: Binance - historical trades - BTCUSDT/limit=500
    url: https://api.binance.us/api/v3/ticker/24hr
  - name: Binance - futures ping
    url: https://api.binance.us/fapi/v1/ping
  - name: Binance - futures server time
    url: https://api.binance.us/fapi/v1/time

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: https://github.com/goquantio/crypto-monitor
  logoUrl: https://res.cloudinary.com/dfsht1snd/image/upload/v1675451285/website/social/goquant.png
  name: Crypto Monitor
  introTitle: "**Crypto Monitor** monitors the cryto exchange apis."
  introMessage: Monitors relate to REST connections and do not include websockets
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
